// Where a job can be done from, as far as the location line its board
// publishes says: "San Francisco, CA, USA", "Berlin, BE, DE", "Remote;
// Europe", "EMEA · remote", "London". The lines follow no one format, so
// they are read for the places they name — countries, their regions and
// cities, the codes some boards abbreviate them to, and stretches of the
// world like EMEA — and a job is placed wherever its line points. This runs
// here rather than in the database: postgres needs seconds for what takes
// milliseconds here, so the api reads just the distinct lines off it.

// the regions a caller can ask for
export const REGIONS = [
	'eu',
	'uk',
	'europe',
	'us',
	'canada',
	'latam',
	'apac',
	'mena',
	'africa'
] as const;
export type Region = (typeof REGIONS)[number];

// what a location line can name: a place in one of the regions — Europe
// split three ways, since the eu (with the countries sharing its free
// movement) and the uk hire differently — or a stretch of the world as a
// whole
type Area =
	| 'eu'
	| 'uk'
	| 'europe-other'
	| 'us'
	| 'canada'
	| 'latam'
	| 'apac'
	| 'mena'
	| 'africa'
	| 'europe'
	| 'emea'
	| 'north-america'
	| 'americas'
	| 'worldwide';

// the areas that put a job within reach of each region: a German job is
// open to the eu, a Europe-wide or EMEA one to the eu and the uk alike, and
// a worldwide one to everybody
const COVERS: Record<Region, Area[]> = {
	eu: ['eu', 'europe', 'emea', 'worldwide'],
	uk: ['uk', 'europe', 'emea', 'worldwide'],
	europe: ['eu', 'uk', 'europe-other', 'europe', 'emea', 'worldwide'],
	us: ['us', 'north-america', 'americas', 'worldwide'],
	canada: ['canada', 'north-america', 'americas', 'worldwide'],
	latam: ['latam', 'americas', 'worldwide'],
	apac: ['apac', 'worldwide'],
	mena: ['mena', 'emea', 'worldwide'],
	africa: ['africa', 'emea', 'worldwide']
};

// a place named after a us (or canadian) one: the name only counts when no
// state follows it — "Paris, TX" and "Vienna, VA" are american
const unlessIn = (states: string) => `(?![\\s,]+(?:${states})(?![a-z0-9]))`;

// how each area is named. Words match in any case as whole words — a space
// stands for any run of spaces and hyphens — and are regex fragments, so a
// few carry a guard. Codes are the two- and three-letter abbreviations the
// boards put last in a place ("Austin, TX", "Paris, FR", "Sydney, NSW"),
// matched in capitals only and only there, so "in" or "de" in a sentence
// never counts. Two letters can be a us state and a country at once: in
// that last place DE is Germany and IN is India on these boards, and every
// other clash is read as the state
const PLACES: Record<Area, { words: string[]; codes?: string[] }> = {
	eu: {
		words: [
			'eu',
			'e\\.u',
			'eea',
			'european union',
			'dach',
			'benelux',
			'nordics?',
			'scandinavia',
			'baltics',
			'baltic states',
			'austria',
			'österreich',
			'belgium',
			'belgique',
			'belgië',
			'bulgaria',
			'croatia',
			'hrvatska',
			'cyprus',
			'czechia',
			'czech republic',
			'denmark',
			'danmark',
			'estonia',
			'finland',
			'suomi',
			'france',
			'germany',
			'deutschland',
			'greece',
			'hungary',
			'(?<!northern[\\s-]+)ireland',
			'italy',
			'italia',
			'latvia',
			'lithuania',
			'luxembourg',
			'malta',
			'netherlands',
			'holland',
			'nederland',
			`poland${unlessIn('oh|ohio|me|maine|ny|in|indiana')}`,
			'polska',
			'portugal',
			'romania',
			'slovakia',
			'slovenia',
			'spain',
			'españa',
			'espana',
			'sweden',
			'sverige',
			'norway',
			'norge',
			'iceland',
			'liechtenstein',
			'switzerland',
			'schweiz',
			'suisse',
			// regions of those countries the boards name without the country
			'bavaria',
			'bayern',
			'hesse',
			'hessen',
			'nordrhein westfalen',
			'north rhine westphalia',
			'baden württemberg',
			'île de france',
			'ile de france',
			'catalonia',
			'catalunya',
			'north holland',
			'noord holland',
			'south holland',
			'zuid holland',
			'flanders',
			'wallonia',
			'leinster',
			'lombardy',
			'lombardia',
			'mazowieckie',
			'masovian',
			'silesian',
			'moravia',
			'moravian',
			// cities, the ambiguous ones guarded against their american namesakes
			`berlin${unlessIn('nh|ct|md|nj|wi|pa|vt|ma')}`,
			'munich',
			'münchen',
			'muenchen',
			`hamburg${unlessIn('ny|ia|pa|mi')}`,
			`frankfurt${unlessIn('ky|il|in|mi')}`,
			'cologne',
			'köln',
			'koeln',
			'düsseldorf',
			'dusseldorf',
			'duesseldorf',
			'stuttgart',
			'leipzig',
			'dresden',
			'hannover',
			'nuremberg',
			'nürnberg',
			'karlsruhe',
			'heidelberg',
			'aachen',
			'freiburg',
			'bonn',
			'mannheim',
			'darmstadt',
			'münster',
			'ottobrunn',
			'garching',
			`vienna${unlessIn('va|virginia|md|oh|wv|ga|il')}`,
			'wien',
			'graz',
			'linz',
			'salzburg',
			'innsbruck',
			`paris${unlessIn('tx|texas|tn|tennessee|ky|kentucky|il|illinois|ar|arkansas|on|ontario|me|maine')}`,
			'lyon',
			'marseille',
			'toulouse',
			'bordeaux',
			'nantes',
			'lille',
			'montpellier',
			'grenoble',
			'rennes',
			'strasbourg',
			'sophia antipolis',
			`amsterdam${unlessIn('ny|new york')}`,
			'rotterdam',
			'utrecht',
			'eindhoven',
			'the hague',
			'den haag',
			'haarlem',
			'delft',
			'leiden',
			'groningen',
			'brussels',
			'bruxelles',
			'brussel',
			'antwerp',
			'antwerpen',
			'ghent',
			'gent',
			'leuven',
			'madrid',
			'barcelona',
			`valencia${unlessIn('ca|california|venezuela')}`,
			'seville',
			'sevilla',
			'málaga',
			'malaga',
			'bilbao',
			'zaragoza',
			'lisbon',
			'lisboa',
			'porto(?![\\s-]+alegre)',
			'braga',
			'coimbra',
			`milan${unlessIn('mi|michigan|tn|tennessee|oh|ohio|in|indiana|mo|missouri|usa|us')}`,
			'milano',
			`rome${unlessIn('ga|georgia|ny|new york|usa|us')}`,
			'roma',
			'turin',
			'torino',
			'bologna',
			'firenze',
			'napoli',
			'genova',
			`dublin${unlessIn('ca|california|oh|ohio|ga|georgia|va|virginia|pa|pennsylvania|tx|texas|nh')}`,
			`cork${unlessIn('ky|kentucky')}`,
			'galway',
			`athens${unlessIn('ga|georgia|oh|ohio|al|alabama|tn|tennessee|tx|texas|pa')}`,
			'thessaloniki',
			'stockholm',
			'gothenburg',
			'göteborg',
			'goteborg',
			'malmö',
			'malmo',
			'uppsala',
			'copenhagen',
			'københavn',
			'aarhus',
			'oslo',
			'trondheim',
			'helsinki',
			'espoo',
			'tampere',
			'oulu',
			'tallinn',
			'tartu',
			'riga',
			'vilnius',
			'kaunas',
			`warsaw${unlessIn('in|indiana|ny|mo|nc|va|ky|oh|il')}`,
			'warszawa',
			'kraków',
			'krakow',
			'cracow',
			'wrocław',
			'wroclaw',
			'gdańsk',
			'gdansk',
			'poznań',
			'poznan',
			'łódź',
			'lodz',
			'katowice',
			'prague',
			'praha',
			'brno',
			'bratislava',
			'budapest',
			'bucharest',
			'bucurești',
			'cluj',
			'iași',
			'iasi',
			'timișoara',
			'timisoara',
			'sofia',
			'plovdiv',
			'zagreb',
			'ljubljana',
			'valletta',
			'nicosia',
			'limassol',
			'larnaca',
			'reykjavik',
			'reykjavík',
			'zürich',
			'zurich',
			`geneva${unlessIn('il|illinois|ny|new york|oh|ohio|al|alabama')}`,
			'genève',
			'geneve',
			'basel',
			'(?<!new[\\s-]+)bern',
			'lausanne',
			'lugano',
			'zug'
		],
		codes: [
			'AT',
			'BE',
			'BG',
			'HR',
			'CY',
			'CZ',
			'DK',
			'EE',
			'FI',
			'FR',
			'DE',
			'GR',
			'HU',
			'IE',
			'IT',
			'LV',
			'LT',
			'LU',
			'NL',
			'PL',
			'PT',
			'RO',
			'SK',
			'SI',
			'ES',
			'SE',
			'IS',
			'LI',
			'NO',
			'CH'
		]
	},
	uk: {
		words: [
			'united kingdom',
			'uk',
			'u\\.k',
			'great britain',
			'britain',
			'(?<!new[\\s-]+)england',
			'scotland',
			`(?<!south[\\s-]+)wales${unlessIn('pa|pennsylvania')}`,
			'northern ireland',
			'gibraltar',
			'isle of man',
			'guernsey',
			`london${unlessIn('on|ontario|ky|kentucky|oh|ohio|ar|arkansas')}`,
			`manchester${unlessIn('ct|connecticut|nh|new hampshire|vt|md|mi|mo|tn|ia|ky|nj|pa')}`,
			`birmingham${unlessIn('al|alabama|mi|michigan')}`,
			'edinburgh',
			`glasgow${unlessIn('ky|kentucky|mt|montana')}`,
			'belfast',
			'cardiff',
			'leeds',
			'liverpool',
			`bristol${unlessIn('pa|pennsylvania|ct|connecticut|tn|tennessee|va|virginia|ri|rhode island|in|wi|nh|vt')}`,
			`oxford${unlessIn('pa|pennsylvania|ms|mississippi|oh|ohio|nc|ct|mi|al|md|ga|ma|nj')}`,
			'newcastle upon tyne',
			'nottingham',
			'sheffield',
			`(?<!new[\\s-]+)brighton${unlessIn('co|colorado|mi|michigan|ma|massachusetts|ny|new york|mn|pa|tn|al|il|ia')}`,
			'milton keynes',
			'guildford',
			'didcot',
			'harwell',
			'stevenage',
			`heathrow${unlessIn('fl|florida')}`,
			'canary wharf',
			'shoreditch'
		],
		codes: ['GB', 'UK']
	},
	'europe-other': {
		words: [
			'albania',
			'andorra',
			'armenia',
			'azerbaijan',
			'belarus',
			'bosnia',
			'kosovo',
			'moldova',
			'monaco',
			'montenegro',
			'north macedonia',
			'macedonia',
			'fyrom',
			'russia',
			'san marino',
			'serbia',
			'turkey',
			'türkiye',
			'turkiye',
			'ukraine',
			'faroe islands',
			'belgrade',
			'beograd',
			'novi sad',
			'sarajevo',
			'podgorica',
			'skopje',
			'tirana',
			'prishtina',
			'pristina',
			'kyiv',
			'kiev',
			'lviv',
			'kharkiv',
			'chisinau',
			'chișinău',
			'minsk',
			'istanbul',
			'İstanbul',
			'ankara',
			'izmir',
			'yerevan',
			'tbilisi',
			'baku'
		],
		codes: ['RS', 'BA', 'MK', 'XK', 'UA', 'BY', 'TR', 'RU', 'AM', 'GE']
	},
	us: {
		words: [
			'united states',
			'usa',
			'u\\.s\\.a',
			'u\\.s',
			'us',
			'alabama',
			'alaska',
			'arizona',
			'arkansas',
			'california',
			'colorado',
			'connecticut',
			'delaware',
			'florida',
			// the country of that name hardly comes up on these boards
			'(?<!tbilisi[\\s,]+)georgia',
			'hawaii',
			'idaho',
			'illinois',
			'indiana',
			'iowa',
			'kansas',
			'kentucky',
			'louisiana',
			'maine',
			'maryland',
			'massachusetts',
			'michigan',
			'minnesota',
			'mississippi',
			'missouri',
			'montana',
			'nebraska',
			'nevada',
			'new hampshire',
			'new jersey',
			'new mexico',
			'new york',
			'north carolina',
			'north dakota',
			'ohio',
			'oklahoma',
			'oregon',
			'pennsylvania',
			'rhode island',
			'south carolina',
			'south dakota',
			'tennessee',
			'texas',
			'utah',
			'vermont',
			'virginia',
			'washington',
			'wisconsin',
			'wyoming',
			'district of columbia',
			'puerto rico',
			'new england',
			'west coast',
			'east coast',
			'midwest',
			'pacific northwest',
			'bay area',
			'silicon valley',
			'san francisco',
			'sf',
			'nyc',
			'manhattan',
			'brooklyn',
			'seattle',
			'boston',
			'chicago',
			'austin',
			'los angeles',
			'denver',
			'atlanta',
			'dallas',
			'houston',
			'miami',
			'philadelphia',
			'pittsburgh',
			'phoenix',
			'san diego',
			'san jos[eé](?![\\s,]+costa)',
			'palo alto',
			'mountain view',
			'menlo park',
			'redwood city',
			'san mateo',
			'sunnyvale',
			'santa clara',
			'oakland',
			'berkeley',
			'santa monica',
			'salt lake city',
			'nashville',
			'raleigh',
			'minneapolis',
			'detroit',
			'baltimore',
			'charlotte',
			'indianapolis',
			'somerville',
			'redmond',
			'bellevue',
			'boulder',
			'irvine',
			'pasadena',
			'plano',
			'tampa',
			'orlando',
			'las vegas',
			'sacramento',
			'tempe',
			'scottsdale',
			'reston',
			'tysons',
			'mclean',
			'herndon',
			'el segundo',
			'long beach',
			'torrance',
			'culver city',
			'jersey city',
			'hoboken',
			'stamford',
			'waltham',
			'woburn',
			'lehi',
			'foster city',
			'san carlos',
			'emeryville',
			'fremont',
			'columbus',
			'portland',
			'st\\.? louis',
			'saint louis'
		],
		codes: [
			'AL',
			'AK',
			'AZ',
			'AR',
			'CA',
			'CO',
			'CT',
			'FL',
			'GA',
			'HI',
			'ID',
			'IL',
			'IA',
			'KS',
			'KY',
			'LA',
			'ME',
			'MD',
			'MA',
			'MI',
			'MN',
			'MS',
			'MO',
			'MT',
			'NE',
			'NV',
			'NH',
			'NJ',
			'NM',
			'NY',
			'NC',
			'ND',
			'OH',
			'OK',
			'OR',
			'PA',
			'RI',
			'SC',
			'SD',
			'TN',
			'TX',
			'UT',
			'VT',
			'VA',
			'WA',
			'WV',
			'WI',
			'WY',
			'DC',
			'PR'
		]
	},
	canada: {
		words: [
			'canada',
			'ontario',
			'quebec',
			'québec',
			'british columbia',
			'alberta',
			'manitoba',
			'saskatchewan',
			'nova scotia',
			'new brunswick',
			'newfoundland',
			'prince edward island',
			'yukon',
			'northwest territories',
			'nunavut',
			'toronto',
			'montreal',
			'montréal',
			`vancouver${unlessIn('wa|washington')}`,
			`ottawa${unlessIn('il|illinois|ks|kansas|oh|ohio')}`,
			'calgary',
			'edmonton',
			'winnipeg',
			`halifax${unlessIn('va|virginia|ma|massachusetts|nc|pa')}`,
			'kitchener',
			'mississauga',
			'burnaby',
			'gatineau'
		],
		codes: ['AB', 'BC', 'MB', 'NB', 'NS', 'ON', 'QC', 'NT', 'NU', 'YT']
	},
	latam: {
		words: [
			'latam',
			'lat am',
			'latin america',
			'south america',
			'central america',
			'caribbean',
			'(?<!new[\\s-]+)mexico',
			'méxico',
			'brazil',
			'brasil',
			'argentina',
			'chile',
			'colombia',
			'peru',
			'perú',
			'uruguay',
			'paraguay',
			'bolivia',
			'ecuador',
			'venezuela',
			'costa rica',
			'panama(?![\\s-]+city)',
			'guatemala',
			'el salvador',
			'honduras',
			'nicaragua',
			'cuba',
			'dominican republic',
			'jamaica',
			'trinidad',
			'são paulo',
			'sao paulo',
			'rio de janeiro',
			'belo horizonte',
			'campinas',
			'curitiba',
			'porto alegre',
			'florianópolis',
			'florianopolis',
			'recife',
			'brasília',
			'brasilia',
			'cdmx',
			'guadalajara',
			'monterrey',
			'querétaro',
			'queretaro',
			'jalisco',
			'nuevo le[oó]n',
			'buenos aires',
			'bogotá',
			'bogota',
			'medellín',
			'medellin',
			'santiago(?![\\s-]+de[\\s-]+compostela)',
			`lima${unlessIn('oh|ohio|pa|ny')}`,
			'montevideo',
			'quito',
			'guayaquil',
			'caracas'
		],
		codes: ['MX', 'BR', 'CL', 'UY', 'EC', 'BO', 'PY', 'VE', 'CR', 'GT', 'SV', 'HN', 'NI', 'DO']
	},
	apac: {
		words: [
			'apac',
			'apj',
			'asia',
			'oceania',
			'anz',
			'asean',
			'india',
			'china',
			'hong kong',
			'hongkong',
			'taiwan',
			'japan',
			'(?<!north[\\s-]+)korea',
			'singapore',
			'malaysia',
			'thailand',
			'vietnam',
			'viet nam',
			'philippines',
			'indonesia',
			'australia',
			'new zealand',
			'pakistan',
			'bangladesh',
			'sri lanka',
			'nepal',
			'cambodia',
			'macau',
			'karnataka',
			'maharashtra',
			'telangana',
			'tamil nadu',
			'haryana',
			'uttar pradesh',
			'kerala',
			'madhya pradesh',
			'gujarat',
			'west bengal',
			'new south wales',
			'queensland',
			'western australia',
			'tasmania',
			'guangdong',
			'jiangsu',
			'zhejiang',
			'selangor',
			'bengaluru',
			'bangalore',
			'hyderabad',
			'pune',
			'mumbai',
			'delhi',
			'gurugram',
			'gurgaon',
			'noida',
			'chennai',
			'kolkata',
			'ahmedabad',
			'indore',
			'kochi',
			'jaipur',
			'chandigarh',
			'coimbatore',
			'tokyo',
			'osaka',
			'seoul',
			'busan',
			`sydney${unlessIn('ns|nova scotia')}`,
			`melbourne${unlessIn('fl|florida|ar|ia|ky')}`,
			'brisbane',
			'canberra',
			'adelaide',
			'auckland',
			'shanghai',
			'beijing',
			'shenzhen',
			'guangzhou',
			'hangzhou',
			'suzhou',
			'chengdu',
			'taipei',
			'hsinchu',
			'manila',
			'makati',
			'cebu',
			'jakarta',
			'bangkok',
			'ho chi minh city',
			'saigon',
			'hanoi',
			'kuala lumpur',
			'penang',
			'karachi',
			'lahore',
			'islamabad',
			'dhaka',
			'colombo',
			'kathmandu',
			'lucknow',
			'kazakhstan',
			'almaty',
			'uzbekistan',
			'tashkent',
			'中国',
			'北京',
			'上海',
			'深圳',
			'广州',
			'杭州',
			'成都',
			'武汉',
			'苏州',
			'南京',
			'西安',
			'重庆',
			'郑州',
			'济南',
			'沈阳',
			'合肥',
			'天津',
			'東京',
			'大阪'
		],
		codes: [
			'IN',
			'CN',
			'HK',
			'TW',
			'JP',
			'KR',
			'SG',
			'MY',
			'TH',
			'VN',
			'PH',
			'AU',
			'NZ',
			'PK',
			'BD',
			'LK',
			'NP',
			'NSW',
			'VIC',
			'QLD',
			'TAS'
		]
	},
	mena: {
		words: [
			'mena',
			'middle east',
			'north africa',
			'gcc',
			'israel',
			'united arab emirates',
			'uae',
			'u\\.a\\.e',
			'saudi arabia',
			'ksa',
			'qatar',
			'kuwait',
			'bahrain',
			'oman',
			'jordan',
			'lebanon',
			'egypt',
			'morocco',
			'tunisia',
			'algeria',
			'tel aviv',
			'jerusalem',
			'haifa',
			'herzliya',
			'ramat gan',
			'petah tikva',
			'petach tikva',
			'gush dan',
			'netanya',
			'rehovot',
			'yokneam',
			'raanana',
			'dubai',
			'abu dhabi',
			'riyadh',
			'jeddah',
			'doha',
			'cairo',
			'amman',
			'beirut',
			'casablanca',
			'rabat',
			'tunis',
			'algiers'
		],
		codes: ['AE', 'SA', 'QA', 'KW', 'BH', 'OM', 'JO', 'LB', 'EG', 'DZ']
	},
	africa: {
		words: [
			'(?<!north[\\s-]+)africa',
			'nigeria',
			'kenya',
			'ghana',
			'rwanda',
			'ethiopia',
			'uganda',
			'tanzania',
			"c[oô]te d'ivoire",
			'ivory coast',
			'senegal',
			'cameroon',
			'zambia',
			'zimbabwe',
			'botswana',
			'namibia',
			'mozambique',
			'mauritius',
			'madagascar',
			'angola',
			'lagos',
			'lekki',
			'abuja',
			'nairobi',
			'cape town',
			'johannesburg',
			'pretoria',
			'durban',
			'accra',
			'kigali',
			'addis ababa',
			'kampala',
			'dar es salaam',
			'abidjan',
			'dakar',
			'congo',
			'kinshasa',
			'niger',
			'niamey',
			'mali',
			'bamako',
			'gambia'
		],
		codes: ['NG', 'KE', 'ZA', 'GH', 'RW', 'ET', 'UG', 'TZ', 'CI', 'SN']
	},
	europe: {
		words: ['europe', 'european(?![\\s-]+side)', 'cee', 'balkans', 'cet', 'cest']
	},
	emea: { words: ['emea'] },
	'north-america': {
		words: ['north america', 'northern america', 'north american', 'noram', 'namer']
	},
	americas: { words: ['americas', 'amer'] },
	worldwide: {
		words: [
			'worldwide',
			'world wide',
			'global(?![\\s-]+city)',
			'globally'
		]
	}
};

// whole words: no ascii letter or digit on either side, so separators,
// hyphens and accented letters all count as breaks
const wordsSource = (words: string[]) =>
	`(?<![a-z0-9])(?:${words.map((w) => w.replaceAll(' ', '[\\s-]+')).join('|')})(?![a-z0-9])`;

// a code closing a place: after a comma, maybe with a zip code, and then
// the end of the line or of one of its places
const codesSource = (codes: string[]) =>
	`,\\s*(?:${codes.join('|')})(?:\\s+\\d{5}(?:-\\d{4})?)?(?=\\s*(?:$|[;·•|/()\\[\\]]|[-–—]\\s))`;

const AREAS = Object.keys(PLACES) as Area[];

// each area as its two patterns
const MATCHERS = AREAS.map((area) => {
	const { words, codes } = PLACES[area];
	return {
		area,
		words: new RegExp(wordsSource(words), 'i'),
		codes: codes ? new RegExp(codesSource(codes)) : null
	};
});

// the regions a location puts a job within reach of; none when it names no
// place at all ("Remote", "Hybrid", an office's name)
export function regionsOf(location: string): Region[] {
	const areas = new Set(
		MATCHERS.filter((m) => m.words.test(location) || m.codes?.test(location)).map((m) => m.area)
	);
	return REGIONS.filter((r) => COVERS[r].some((a) => areas.has(a)));
}

// whether a location's regions (from regionsOf) meet any of the wanted
// ones — 'unknown' standing for the lines that name no place
export const inRegions = (regions: Region[], wanted: readonly (Region | 'unknown')[]) =>
	regions.length === 0 ? wanted.includes('unknown') : regions.some((r) => wanted.includes(r));

// a line saying the job is remote
const REMOTE = new RegExp(
	wordsSource([
		'remote',
		'remotely',
		'anywhere',
		'virtual',
		'wfh',
		'work from home',
		'working from home',
		'home based',
		'telework',
		'teleworking',
		'telecommute'
	]),
	'i'
);
export const isRemote = (location: string) => REMOTE.test(location);
