// The tracked funds — each runs a public job board listing the openings at
// its portfolio companies. Slugs match the scraper module filenames in
// src/server/scrapers/; url is the board's job listing page.
export interface FundInfo {
	slug: string;
	name: string;
	url: string;
}

export const FUNDS: FundInfo[] = [
	{ slug: '01a', name: '01 Advisors', url: 'https://jobs.01a.com/jobs' },
	{ slug: '2150', name: '2150', url: 'https://2150.getro.com/jobs' },
	{ slug: '8vc', name: '8VC', url: 'https://jobs.8vc.com/jobs' },
	{ slug: 'accel', name: 'Accel', url: 'https://jobs.accel.com/jobs' },
	{ slug: 'airbus', name: 'Airbus Ventures', url: 'https://jobs.airbusventures.vc/jobs' },
	{ slug: 'a16z', name: 'Andreessen Horowitz', url: 'https://jobs.a16z.com/jobs' },
	{ slug: 'avp', name: 'AVP', url: 'https://jobs.avpcap.com/jobs' },
	{ slug: 'b2venture', name: 'b2venture', url: 'https://jobs.b2venture.vc/jobs' },
	{ slug: 'balderton', name: 'Balderton Capital', url: 'https://careers.balderton.com/jobs' },
	{ slug: 'base10', name: 'Base10', url: 'https://careers.base10.vc/jobs' },
	{ slug: 'battery', name: 'Battery Ventures', url: 'https://jobs.battery.com/jobs' },
	{ slug: 'bessemer', name: 'Bessemer Venture Partners', url: 'https://jobs.bvp.com/jobs' },
	{ slug: 'canapi', name: 'Canapi Ventures', url: 'https://careers.canapi.com/jobs' },
	{ slug: 'cherry', name: 'Cherry Ventures', url: 'https://talent.cherry.vc/jobs' },
	{ slug: 'congruent', name: 'Congruent Ventures', url: 'https://jobs.congruentvc.com/jobs' },
	{ slug: 'craft', name: 'Craft Ventures', url: 'https://jobs.craftventures.com/jobs' },
	{ slug: 'creandum', name: 'Creandum', url: 'https://careers.creandum.com/jobs' },
	{ slug: 'dcvc', name: 'DCVC', url: 'https://jobs.dcvc.com/jobs' },
	{ slug: 'e14', name: 'E14 Fund', url: 'https://jobs.e14.vc/jobs' },
	{ slug: 'earlybird', name: 'Earlybird Venture Capital', url: 'https://jobs.earlybird.com/jobs' },
	{ slug: 'emergence', name: 'Emergence Capital', url: 'https://talent.emcap.com/jobs' },
	{ slug: 'f2', name: 'F2 Venture Capital', url: 'https://jobs.f2vc.com/jobs' },
	{ slug: 'felicis', name: 'Felicis', url: 'https://jobs.felicis.com/jobs' },
	{ slug: 'firstround', name: 'First Round Capital', url: 'https://jobs.firstround.com/jobs' },
	{ slug: 'flagship', name: 'Flagship Pioneering', url: 'https://www.flagshippioneering.com/join/roles' },
	{ slug: 'foundation', name: 'Foundation Capital', url: 'https://jobs.foundationcapital.com/jobs' },
	{ slug: 'generalcatalyst', name: 'General Catalyst', url: 'https://jobs.generalcatalyst.com/jobs' },
	{ slug: 'greycroft', name: 'Greycroft', url: 'https://jobs.greycroft.com/jobs' },
	{ slug: 'greylock', name: 'Greylock', url: 'https://greylock.com/jobs/portfolio-jobs/' },
	{ slug: 'grove', name: 'Grove Ventures', url: 'https://careers.grovevc.com/jobs' },
	{ slug: 'gv', name: 'GV', url: 'https://jobs.gv.com/jobs' },
	{ slug: 'headline', name: 'Headline', url: 'https://jobs.headline.com/jobs' },
	{ slug: 'htgf', name: 'HTGF', url: 'https://startupjobs.htgf.de/jobs' },
	{ slug: 'hvcapital', name: 'HV Capital', url: 'https://jobs.hvcapital.com/jobs' },
	{ slug: 'indexventures', name: 'Index Ventures', url: 'https://indexventures.getro.com/jobs' },
	{ slug: 'insight', name: 'Insight Partners', url: 'https://jobs.insightpartners.com/jobs' },
	{ slug: 'ivp', name: 'IVP', url: 'https://careers.ivp.com/jobs' },
	{ slug: 'khosla', name: 'Khosla Ventures', url: 'https://jobs.khoslaventures.com/jobs' },
	{ slug: 'lakestar', name: 'Lakestar', url: 'https://consider.com/boards/vc/lakestar/jobs' },
	{ slug: 'lightspeed', name: 'Lightspeed Venture Partners', url: 'https://jobs.lsvp.com/jobs' },
	{ slug: 'lux', name: 'Lux Capital', url: 'https://jobs.luxcapital.com/jobs' },
	{ slug: 'mseq', name: 'Main Sequence', url: 'https://jobs.mseq.vc/' },
	{ slug: 'makers', name: 'Makers Fund', url: 'https://jobs.makersfund.com/jobs' },
	{ slug: 'mantis', name: 'Mantis VC', url: 'https://careers.mantisvc.com/jobs' },
	{ slug: 'moc', name: 'Market One Capital', url: 'https://jobs.moc.vc/jobs' },
	{ slug: 'massmutual', name: 'MassMutual Ventures', url: 'https://jobs.massmutualventures.com/jobs' },
	{ slug: 'matchstick', name: 'Matchstick Ventures', url: 'https://jobs.matchstickventures.com/jobs' },
	{ slug: 'maveron', name: 'Maveron', url: 'https://jobs.maveron.com/jobs' },
	{ slug: 'mayfield', name: 'Mayfield', url: 'https://mayfield.getro.com/jobs' },
	{ slug: 'mcj', name: 'MCJ', url: 'https://jobs.mcj.vc/jobs' },
	{ slug: 'menlo', name: 'Menlo Ventures', url: 'https://jobs.menlovc.com/jobs' },
	{ slug: 'meron', name: 'Meron Capital', url: 'https://www.meron.vc/jobs' },
	{ slug: 'metaprop', name: 'MetaProp', url: 'https://jobs.metaprop.com/jobs' },
	{ slug: 'orbit', name: 'MIT Orbit', url: 'https://jobs.orbit.mit.edu/jobs' },
	{ slug: 'mmc', name: 'MMC Ventures', url: 'https://jobs.mmc.vc/jobs' },
	{ slug: 'moderne', name: 'Moderne Ventures', url: 'https://portfoliocareers.moderneventures.com/jobs' },
	{ slug: 'moneta', name: 'Moneta Ventures', url: 'https://jobs.moneta.vc/jobs' },
	{ slug: 'morpheus', name: 'Morpheus', url: 'https://jobs.morpheus.com/jobs' },
	{ slug: 'moxxie', name: 'Moxxie Ventures', url: 'https://careers.moxxie.vc/jobs' },
	{ slug: 'necessary', name: 'Necessary Ventures', url: 'https://jobs.necessary.vc/jobs' },
	{ slug: 'nea', name: 'New Enterprise Associates', url: 'https://careers.nea.com/jobs' },
	{ slug: 'newmarkets', name: 'New Markets Venture Partners', url: 'https://jobs.newmarketsvp.com/jobs' },
	{ slug: 'newfund', name: 'Newfund Capital', url: 'https://jobs.newfundcap.com/jobs' },
	{ slug: 'nextview', name: 'NextView Ventures', url: 'https://jobs.nextview.vc/jobs' },
	{ slug: 'nfx', name: 'NFX', url: 'https://jobs.nfx.com/jobs' },
	{ slug: 'northzone', name: 'Northzone', url: 'https://portfolio.northzone.com/jobs' },
	{ slug: 'norwest', name: 'Norwest Venture Partners', url: 'https://careers.norwest.com/jobs' },
	{ slug: 'nyca', name: 'NYCA Partners', url: 'https://jobs.nyca.com/jobs' },
	{ slug: 'octopus', name: 'Octopus Ventures', url: 'https://talent.octopusventures.com/jobs' },
	{ slug: 'offline', name: 'Offline Ventures', url: 'https://jobs.offline.vc/jobs' },
	{ slug: 'omnivore', name: 'Omnivore', url: 'https://jobs.omnivore.vc/jobs' },
	{ slug: 'origin', name: 'Origin Ventures', url: 'https://jobs.originventures.com/jobs' },
	{ slug: 'outsiders', name: 'Outsiders Fund', url: 'https://jobs.outsidersfund.com/jobs' },
	{ slug: 'paleblue', name: 'Pale Blue Dot', url: 'https://paleblue.vc/jobs' },
	{ slug: 'paypal', name: 'PayPal Ventures', url: 'https://jobs.paypal.vc/jobs' },
	{ slug: 'pear', name: 'Pear VC', url: 'https://jobs.ashbyhq.com/Pear-VC' },
	{ slug: 'playground', name: 'Playground Global', url: 'https://careers.playground.global/jobs' },
	{ slug: 'plugandplay', name: 'Plug and Play', url: 'https://jobs.pnptc.com/jobs' },
	{ slug: 'point72', name: 'Point72', url: 'https://careers.point72.com/' },
	{ slug: 'primary', name: 'Primary Venture Partners', url: 'https://jobs.primary.vc/jobs' },
	{ slug: 'qed', name: 'QED Investors', url: 'https://careers.qedinvestors.com/jobs' },
	{ slug: 'quiet', name: 'Quiet Capital', url: 'https://careers.quiet.com/jobs' },
	{ slug: 'qumra', name: 'Qumra Capital', url: 'https://jobs.qumracapital.com/jobs' },
	{ slug: 'radian', name: 'Radian Capital', url: 'https://careers.radiancapital.com/jobs' },
	{ slug: 'radical', name: 'Radical Ventures', url: 'https://radical.getro.com/jobs' },
	{ slug: 'rainfall', name: 'Rainfall', url: 'https://careers.rainfall.com/jobs' },
	{ slug: 'rally', name: 'Rally Ventures', url: 'https://jobs.rallyventures.com/jobs' },
	{ slug: 'reach', name: 'Reach Capital', url: 'https://jobs.reachcapital.com/jobs' },
	{ slug: 'redsea', name: 'Red Sea Ventures', url: 'https://jobs.redseaventures.com/jobs' },
	{ slug: 'redpoint', name: 'Redpoint Ventures', url: 'https://careers.redpoint.com/jobs' },
	{ slug: 'ret', name: 'RET Ventures', url: 'https://jobs.ret.vc/jobs' },
	{ slug: 'riverpark', name: 'RiverPark Ventures', url: 'https://jobs.riverparkvc.com/jobs' },
	{ slug: 'rockhealth', name: 'Rock Health Capital', url: 'https://rockhealthcapital.com/job-board/' },
	{ slug: 'rre', name: 'RRE Ventures', url: 'https://jobs.rre.com/jobs' },
	{ slug: 's2g', name: 'S2G Investments', url: 'https://www.s2ginvestments.com/team/careers/open-positions' },
	{ slug: 's3vc', name: 'S3 Ventures', url: 'https://jobs.s3vc.com/jobs' },
	{ slug: 'sandbox', name: 'Sandbox Industries', url: 'https://jobs.sandboxindustries.com/jobs' },
	{ slug: 'scifi', name: 'SciFi VC', url: 'https://scifi.vc/#jobs' },
	{ slug: 'scribble', name: 'Scribble Ventures', url: 'https://jobs.scribble.vc/jobs' },
	{ slug: 'seedcamp', name: 'Seedcamp', url: 'https://talent.seedcamp.com/jobs' },
	{ slug: 'sentiero', name: 'Sentiero Ventures', url: 'https://adde.sentiero.vc/public/jobs' },
	{ slug: 'sequoia', name: 'Sequoia Capital', url: 'https://jobs.sequoiacap.com/jobs' },
	{ slug: 'shield', name: 'Shield Capital', url: 'https://portfoliocareers.shieldcap.com/jobs' },
	{ slug: 'shima', name: 'Shima Capital', url: 'https://jobs.shima.capital/jobs' },
	{ slug: 'sixty8', name: 'Sixty8 Capital', url: 'https://jobs.sixty8.capital/jobs' },
	{ slug: 'socialleverage', name: 'Social Leverage', url: 'https://jobs.socialleverage.com/jobs' },
	{ slug: 'sogal', name: 'SoGal Ventures', url: 'https://jobs.sogalventures.com/jobs' },
	{ slug: 'soma', name: 'Soma Capital', url: 'https://jobs.somacap.com/jobs' },
	{ slug: 'sosv', name: 'SOSV', url: 'https://techjobs.sosv.com/jobs' },
	{ slug: 'speedinvest', name: 'Speedinvest', url: 'https://careers.speedinvest.com/jobs' },
	{ slug: 'springtide', name: 'SpringTide Ventures', url: 'https://jobs.springtide.com/jobs' },
	{ slug: 'springtime', name: 'SpringTime Ventures', url: 'https://careers.springtimeventures.com/jobs' },
	{ slug: 'stageone', name: 'StageOne Ventures', url: 'https://jobs.stageonevc.com/' },
	{ slug: 'supermoon', name: 'Supermoon Capital', url: 'https://jobs.supermooncapital.com/jobs' },
	{ slug: 'tau', name: 'Tau Ventures', url: 'https://www.tauventures.com/careers' },
	{ slug: 'techstars', name: 'Techstars', url: 'https://jobs.techstars.com/jobs' },
	{ slug: 'thirdrock', name: 'Third Rock Ventures', url: 'https://jobs.thirdrockventures.com/jobs' },
	{ slug: 'tlv', name: 'TLV Partners', url: 'https://jobs.tlv.partners/jobs' },
	{ slug: 'toyota', name: 'Toyota Ventures', url: 'https://jobs.toyota.ventures/jobs' },
	{ slug: 'trailhead', name: 'Trailhead Capital', url: 'https://trailheadcap.getro.com/jobs' },
	{ slug: 'transform', name: 'Transformation Capital', url: 'https://careers.transformcap.com/jobs' },
	{ slug: 'transition', name: 'Transition Ventures', url: 'https://jobs.transition.vc/jobs' },
	{ slug: 'trueventures', name: 'True Ventures', url: 'https://jobs.trueventures.com/jobs' },
	{ slug: 'tsvc', name: 'TSVC', url: 'https://www.tsvcap.com/jobs' },
	{ slug: 'tusk', name: 'Tusk Venture Partners', url: 'https://jobs.tusk.vc/jobs' },
	{ slug: 'type1', name: 'Type One Ventures', url: 'https://jobs.type1ventures.com/jobs' },
	{ slug: 'ulu', name: 'Ulu Ventures', url: 'https://jobs.uluventures.com/jobs' },
	{ slug: 'uncork', name: 'Uncork Capital', url: 'https://jobs.uncorkcapital.com/jobs' },
	{ slug: 'underline', name: 'Underline Ventures', url: 'https://underline.vc/jobs' },
	{ slug: 'upfront', name: 'Upfront Ventures', url: 'https://jobs.upfront.com/jobs' },
	{ slug: 'urban', name: 'Urban Innovation Fund', url: 'https://jobs.urban.vc/jobs' },
	{ slug: 'usv', name: 'Union Square Ventures', url: 'https://jobs.usv.com/jobs' },
	{ slug: 'vamos', name: 'VamosVentures', url: 'https://jobs.vamosventures.com/jobs' },
	{ slug: 'venrock', name: 'Venrock', url: 'https://jobs.venrock.com/jobs' },
	{ slug: 'vertex', name: 'Vertex Ventures Israel', url: 'https://jobs.vertexventures.co.il/jobs' },
	{ slug: 'vestigo', name: 'Vestigo Ventures', url: 'https://jobs.vestigoventures.com/jobs' },
	{ slug: 'viola', name: 'Viola Group', url: 'https://careers.viola-group.com/jobs' },
	{ slug: 'visiblehands', name: 'Visible Hands', url: 'https://jobs.visiblehands.vc/jobs' },
	{ slug: 'visible', name: 'Visible Ventures', url: 'https://visibleventures.com/jobs/' },
	{ slug: 'voyager', name: 'Voyager Ventures', url: 'https://careers.voyagervc.com/jobs' },
	{ slug: 'willow', name: 'Willow Growth Partners', url: 'https://willowgrowth.com/talent/' },
	{ slug: 'wing', name: 'Wing Venture Capital', url: 'https://careers.wing.vc/jobs' },
	{ slug: 'xange', name: 'XAnge', url: 'https://www.welcometothejungle.com/en/companies-v1/xange/jobs' },
	{ slug: 'xfund', name: 'Xfund', url: 'https://www.xfund.com/jobs' },
	{ slug: 'xrc', name: 'XRC Ventures', url: 'https://careers.xrcventures.com/jobs' },
	{ slug: 'ycombinator', name: 'Y Combinator', url: 'https://www.ycombinator.com/jobs' },
	{ slug: 'zetta', name: 'Zetta Venture Partners', url: 'https://careers.zettavp.com/jobs' }
];

export const fundName = new Map(FUNDS.map((f) => [f.slug, f.name]));
export const fundBySlug = new Map(FUNDS.map((f) => [f.slug, f]));
